"""Person A pipeline: data -> preprocessing -> baselines -> evaluation -> PCA / plots.

    python run_person_a.py

Takes about a minute. Writes:
  data/processed/*.csv   cleaned datasets with a fixed train/test split (Person B uses these)
  results/*.csv, results/summary.md, results/metrics.json
  figures/*.png
"""
import json
import time
import warnings

import pandas as pd
from sklearn.exceptions import ConvergenceWarning

from src import config, plots
from src.baselines import (baseline_models, compare_scaling, describe_params, test_scores, tune_logistic,
                           tune_rbf_svm)
from src.data import add_split, load_paper_toy, load_playlists, save_processed
from src.evaluate import confusion, per_playlist_report, summary_row, top_confusions

warnings.filterwarnings("ignore", category=ConvergenceWarning)
R = config.RESULTS_DIR


def save_csv(df, name):
    R.mkdir(parents=True, exist_ok=True)
    df.to_csv(R / name, index=False, float_format="%.4f")


def md_table(df, digits=3):
    return df.to_markdown(index=False, floatfmt=f".{digits}f")


def section(title):
    print(f"\n=== {title} " + "=" * max(0, 60 - len(title)))


def main():
    t0 = time.time()
    metrics, md = {}, ["# Person A results\n", "_Generated by `python run_person_a.py`. All numbers below come from this run._\n"]

    # ------------------------------------------------------------------ data
    section("1. Data")
    datasets, logs = {}, {}
    for name, playlists in [("main", config.MAIN_PLAYLISTS), ("easy", config.EASY_PLAYLISTS),
                            ("hard", config.HARD_PLAYLISTS)]:
        print(f" {name}:")
        df, logs[name] = load_playlists(playlists)
        datasets[name] = add_split(df)
        save_processed(datasets[name], name)
    try:
        datasets["paper_toy"] = add_split(load_paper_toy())
        save_processed(datasets["paper_toy"], "paper_toy")
        print(f" paper_toy: {len(datasets['paper_toy'])} tracks")
    except FileNotFoundError as e:
        print(" skipping paper toy set:", e)
    metrics["cleaning"] = logs

    main_df = datasets["main"]
    train, test = main_df[main_df.split == "train"], main_df[main_df.split == "test"]
    print(f" main split: {len(train)} train / {len(test)} test")
    n_genres = len(set("|".join(main_df["genres"]).split("|")) - {""})
    metrics["main"] = {"tracks": len(main_df), "playlists": main_df.playlist.nunique(), "train": len(train),
                       "test": len(test), "distinct_genre_tags": n_genres,
                       "tracks_with_genre_tags": round(float(main_df.has_genre.mean()), 3)}

    md += ["## 1. Data\n",
           f"Main set: **{len(main_df)} tracks** in **{main_df.playlist.nunique()} playlists**, "
           f"{n_genres} distinct genre tags, {main_df.has_genre.mean():.0%} of tracks have at least one tag. "
           f"Split 80/20 stratified -> {len(train)} train / {len(test)} test.\n",
           "Cleaning log (main): " + ", ".join(f"{k} = {v}" for k, v in logs["main"].items()) + "\n",
           md_table(main_df.groupby("playlist").agg(tracks=("track_id", "size"),
                                                    with_genre_tags=("has_genre", "mean")).reset_index(), 2), ""]

    plots.class_balance(main_df)
    plots.feature_scales(main_df)
    plots.correlation(main_df)

    # ---------------------------------------------------- scaled vs unscaled
    section("2. Preprocessing: scaled vs unscaled (5-fold CV on the training split)")
    table1 = compare_scaling(train)
    print(table1.round(3).to_string(index=False))
    save_csv(table1, "table1_scaled_vs_unscaled.csv")
    plots.scaled_vs_unscaled(table1)
    metrics["scaled_vs_unscaled"] = table1.round(4).to_dict(orient="records")
    md += ["## 2. Scaled vs unscaled features (paper's Table 1)\n",
           f"{config.CV_FOLDS}-fold stratified CV on the training split, default hyper-parameters. "
           "`all` = standardise every column (what the paper did), `audio` = standardise the 10 audio "
           "features but keep the genre one-hots as 0/1, `none` = raw features.\n",
           md_table(table1), ""]

    # ------------------------------------------------- genres ablation
    section("3. Do the genre tags help? (5-fold CV)")
    abl = compare_scaling(train, use_genres=False, variants=("all",))[["model", "cv_mean_all", "cv_std_all"]]
    abl.columns = ["model", "audio_only", "audio_only_std"]
    abl = abl.merge(table1[["model", "cv_mean_all", "cv_mean_audio"]].rename(
        columns={"cv_mean_all": "with_genres_scale_all", "cv_mean_audio": "with_genres_scale_audio"}))
    abl["best_gain"] = abl[["with_genres_scale_all", "with_genres_scale_audio"]].max(axis=1) - abl["audio_only"]
    print(abl.round(3).to_string(index=False))
    save_csv(abl, "table2_genre_ablation.csv")
    metrics["genre_ablation"] = abl.round(4).to_dict(orient="records")
    md += ["## 3. Audio only vs audio + one-hot genres\n",
           "Audio-only features are standardised (for 10 dense features `all` and `audio` are the same thing).\n",
           md_table(abl), ""]

    # ------------------------------------------------- tuning + test set
    section("4. Tuning and held-out test scores")
    rbf = tune_rbf_svm(train)
    lr = tune_logistic(train)
    rbf_p, lr_p = describe_params(rbf), describe_params(lr)
    print(f" RBF SVM best {rbf_p}  cv={rbf.best_score_:.3f}")
    print(f" LogReg  best {lr_p}  cv={lr.best_score_:.3f}")
    plain = baseline_models()
    s_all, _ = test_scores(train, test, plain, scale="all")
    s_audio, _ = test_scores(train, test, plain, scale="audio")
    scores = s_all.merge(s_audio, on="model", suffixes=("_scale_all", "_scale_audio"))
    tuned_scores, fitted = test_scores(train, test, {"RBF SVM (tuned)": rbf.best_estimator_,
                                                     "Logistic Regression (tuned)": lr.best_estimator_})
    tuned_scores["cv_acc"] = [rbf.best_score_, lr.best_score_]
    tuned_scores["chosen_params"] = [str(rbf_p), str(lr_p)]
    print(scores.round(3).to_string(index=False)); print(tuned_scores.round(3).to_string(index=False))
    save_csv(scores, "table3_test_scores_default.csv")
    save_csv(tuned_scores, "table3b_test_scores_tuned.csv")

    # choose the final baseline by CV score, never by test score
    best_name = "RBF SVM (tuned)" if rbf.best_score_ >= lr.best_score_ else "Logistic Regression (tuned)"
    best = fitted[best_name]
    pred = best.predict(test)
    labels = sorted(main_df.playlist.unique())
    summ = summary_row(test["playlist"], pred)
    print(f" best baseline (chosen on CV): {best_name}  ->  " + ", ".join(f"{k}={v:.3f}" for k, v in summ.items()))
    metrics["tuning"] = {"rbf_svm": {"params": rbf_p, "cv": rbf.best_score_},
                         "logistic": {"params": lr_p, "cv": lr.best_score_}}
    metrics["test_scores_default"] = scores.round(4).to_dict(orient="records")
    metrics["test_scores_tuned"] = tuned_scores.round(4).to_dict(orient="records")
    metrics["best_baseline"] = {"model": best_name, **{k: round(v, 4) for k, v in summ.items()}}
    md += ["## 4. Baselines on the held-out test set\n",
           "Default hyper-parameters, trained on the full training split, scored once on the test split:\n",
           md_table(scores), "",
           "Tuned with grid search (5-fold CV on train; the scaling variant is part of the grid):\n",
           md_table(tuned_scores), "",
           f"**Best baseline (picked on CV score, not test score): {best_name}** - test accuracy "
           f"**{summ['accuracy']:.3f}**, macro F1 {summ['macro_f1']:.3f}.\n"]

    # ------------------------------------------------- per-playlist evaluation
    section("5. Per-playlist metrics and confusion matrix")
    rep = per_playlist_report(test["playlist"], pred, labels)
    cm = confusion(test["playlist"], pred, labels)
    tops = top_confusions(cm)
    print(rep.round(2).to_string(index=False)); print(tops.round(2).to_string(index=False))
    save_csv(rep, "table4_per_playlist.csv")
    save_csv(cm.reset_index(names="true"), "confusion_matrix.csv")
    plots.confusion_matrix_plot(cm, title=f"Confusion matrix: {best_name}\ntest set, each row sums to 1")
    plots.per_playlist_scores(rep, title=f"Per-playlist scores: {best_name}, test set")
    metrics["per_playlist"] = rep.round(4).to_dict(orient="records")
    metrics["top_confusions"] = tops.round(4).to_dict(orient="records")
    # are the mistakes concentrated on songs whose artist has no genre tags?
    tagged = test["has_genre"].to_numpy()
    wrong = pred != test["playlist"].to_numpy()
    lofi = wrong & pd.Series(pred).isin(["Jazz Vibes", "Lush Lofi"]).to_numpy()
    tag_err = {"error_rate_with_tags": float(wrong[tagged].mean()), "n_with_tags": int(tagged.sum()),
               "error_rate_without_tags": float(wrong[~tagged].mean()), "n_without_tags": int((~tagged).sum()),
               "wrongly_sent_to_jazz_or_lofi": int(lofi.sum()),
               "of_those_without_tags": int((lofi & ~tagged).sum())}
    print(" missing genre tags:", tag_err)
    metrics["missing_tag_errors"] = tag_err
    md += ["## 5. Per-playlist precision / recall / F1 (paper's Table 2)\n", md_table(rep), "",
           "Most common mistakes (fraction of the true playlist's test songs):\n", md_table(tops, 2), "",
           f"Test error rate for songs whose artist has genre tags: **{tag_err['error_rate_with_tags']:.1%}** "
           f"(n={tag_err['n_with_tags']}); for songs with no tags: **{tag_err['error_rate_without_tags']:.1%}** "
           f"(n={tag_err['n_without_tags']}). Of the {tag_err['wrongly_sent_to_jazz_or_lofi']} songs wrongly put "
           f"into Jazz Vibes / Lush Lofi, {tag_err['of_those_without_tags']} had no genre tags: those two "
           "playlists are mostly untagged lofi producers, so the model partly learned \"no tags -> lofi\".\n"]

    # ------------------------------------------------- PCA, easy vs hard
    section("6. PCA and separable vs overlapping playlists")
    plots.pca_small_multiples(main_df, use_genres=False)
    plots.pca_small_multiples(main_df, name="07b_pca_main_with_genres.png", use_genres=True)
    accs = {}
    for name in ("easy", "hard"):
        d = datasets[name]
        tr, te = d[d.split == "train"], d[d.split == "test"]
        s = tune_rbf_svm(tr)
        accs[name] = s.best_estimator_.score(te, te["playlist"])
        print(f" {name}: {len(d)} tracks, tuned RBF SVM test accuracy {accs[name]:.3f}")
    plots.pca_easy_vs_hard(datasets["easy"], datasets["hard"], accs)
    metrics["easy_vs_hard"] = {k: round(v, 4) for k, v in accs.items()}
    md += ["## 6. Separable vs overlapping playlists (paper's Fig. 3)\n",
           f"Tuned RBF SVM test accuracy - easy set (5 different genres): **{accs['easy']:.3f}**, "
           f"hard set (5 hip-hop playlists): **{accs['hard']:.3f}**. See `figures/08_pca_easy_vs_hard.png`.\n"]

    # ------------------------------------------------- paper toy set
    if "paper_toy" in datasets:
        section("7. Sanity check on the paper's own playlists")
        d = datasets["paper_toy"]
        tr, te = d[d.split == "train"], d[d.split == "test"]
        t_toy = compare_scaling(tr)
        s = tune_rbf_svm(tr)
        toy_acc = s.best_estimator_.score(te, te["playlist"])
        print(t_toy.round(3).to_string(index=False)); print(f" tuned RBF SVM test accuracy {toy_acc:.3f}")
        save_csv(t_toy, "table5_paper_toy_scaled_vs_unscaled.csv")
        plots.scaled_vs_unscaled(t_toy, name="09_paper_toy_scaled_vs_unscaled.png",
                                 title="Same experiment on the paper's own 13 playlists")
        metrics["paper_toy"] = {"tracks": len(d), "scaled_vs_unscaled": t_toy.round(4).to_dict(orient="records"),
                                "rbf_svm_tuned_test_acc": round(toy_acc, 4)}
        md += ["## 7. Sanity check: the paper's own 13 playlists\n",
               f"{len(d)} of the paper's 1027 tracks could be matched to audio features "
               "(see `scripts/build_paper_toy.py`).\n",
               md_table(t_toy), "", f"Tuned RBF SVM test accuracy: **{toy_acc:.3f}** "
               "(paper: 0.80 ± 0.05 with 5-fold CV on 1044 tracks).\n"]

    R.mkdir(parents=True, exist_ok=True)
    (R / "summary.md").write_text("\n".join(md), encoding="utf-8")
    (R / "metrics.json").write_text(json.dumps(metrics, indent=2, default=str), encoding="utf-8")
    print(f"\nDone in {time.time() - t0:.0f}s. See results/summary.md and figures/.")


if __name__ == "__main__":
    pd.set_option("display.width", 160)
    main()
